apiVersion: apps/v1
kind: Deployment
metadata:
  name: evilsaint-docs
  namespace: default
spec:
  selector:
    matchLabels:
      app: evilsaint-docs
  replicas: 3
  progressDeadlineSeconds: 600
  revisionHistoryLimit: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 1
  template:
    metadata:
      labels:
        app: evilsaint-docs
      annotations:
        deploy-date: "deploy-date-value"
    spec:
      containers:
      - name: evilsaint-docs
        image: "registry-value:latest"
        resources:
          requests:
            memory: "64Mi"
            cpu: "100m"
          limits: 
            memory: "128Mi"
            cpu: "250m" 
        ports: 
        - containerPort: 80
      imagePullSecrets: 
      - name: registry-credentials-gitlab
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: network
                    operator: In
                    values:
                      - servers-untrusted
